apiVersion: apps/v1
kind: Deployment
metadata:
  name: proyecto-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proyecto
  template:
    metadata:
      labels:
        app: proyecto
    spec:
      containers:
      - name: proyecto
        image: 659026651741.dkr.ecr.us-east-1.amazonaws.com/asg
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: proyecto
    k8s-app: proyecto
  name: proyecto
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: proyecto
